# Numpy for Machine Learning
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# Python Lists:
• The list can be homogeneous or heterogeneous.
• Element wise operation is not possible on the list.
• Python list is by default 4 dimensional. But we can create an N-Dimensional list. But then too it will be 4 D list storing another 4D list
• Elements of a list need not be contiguous in memory.

# Numpy
• consumes less memory.
• fast as compared to the python List.
• convenient to use.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

In [3]:
x = np.random.randint(10,size=(3,4,5)) # 10 is for number generating between 0-9

In [4]:
x

array([[[2, 3, 7, 2, 3],
        [2, 5, 3, 0, 7],
        [5, 1, 2, 3, 2],
        [7, 9, 0, 4, 9]],

       [[1, 3, 3, 6, 6],
        [7, 7, 8, 7, 6],
        [0, 7, 7, 7, 4],
        [2, 7, 9, 3, 3]],

       [[3, 6, 6, 4, 7],
        [3, 6, 6, 2, 8],
        [9, 8, 3, 2, 5],
        [6, 2, 2, 0, 1]]])

In [5]:
x.shape 

(3, 4, 5)

In [6]:
x.size #number of elements in the array 

60

In [7]:
x.ndim #dimension

3

In [8]:
x.dtype #data type of integers 

dtype('int32')

In [9]:
x.itemsize # 4 is bytes 

4

In [10]:
x.nbytes # 4 * 60 = 240 Total size of array elements 

240

# Creating Array

In [11]:
# np.array(object, dtype=None, copy=True, order='k', subok=False, ndim=0)

In [13]:
x = np.array(object=[1,2,3,4,5])

In [14]:
type(x)

numpy.ndarray

In [15]:
x

array([1, 2, 3, 4, 5])

In [16]:
x.dtype

dtype('int32')

In [17]:
x = np.array(object=[1,2,3,4,5], dtype = complex)

In [18]:
x.dtype

dtype('complex128')

In [19]:
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [20]:
y = np.array((1,2,3,4,5,6,7))
y

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
type(y)

numpy.ndarray

# Create Array from Scratch

In [23]:
np.zeros((4,5), dtype='int') #return a new array of given shape and type, filled with zeroes.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones((3,3)) #array filled with 1 of given shape

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.full(shape=(4,5),fill_value= 3.1456) #array filled with given value of given shape

array([[3.1456, 3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456, 3.1456]])

In [28]:
np.arange(0,20,2) #generate the array of numbers between 0-20 with step size of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.linspace(0,1,5) #5 equal space value between 0-1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
np.random.random((3,3)) #uniform distribution

array([[0.44189552, 0.04833221, 0.89977438],
       [0.62411554, 0.73288846, 0.12270788],
       [0.07848525, 0.79832875, 0.61568384]])

In [31]:
np.random.normal(0,1,(3,3)) #generate normal random value between 0-1 of shape (3,3)

array([[-1.04775043,  0.18312525,  0.01056933],
       [ 0.52815911, -0.39500118,  0.73273239],
       [-1.94545169,  1.13607057,  0.3887723 ]])

In [32]:
np.random.randint(10,100,size=(2,3)) #generated number between 10-100 of shape(2,3)

array([[22, 33, 73],
       [61, 39, 34]])

In [33]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.empty((3,4)) #new array of given shape without initializing (number which are currently present in memory)

array([[1.16720962e-311, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.18831764e-312, 8.60952352e-072, 5.58407983e-091,
        1.68742789e+160],
       [1.26141891e-076, 1.25780646e-071, 6.48224659e+170,
        5.82471487e+257]])

# Indexing and Slicing

In [36]:
# Data type for a numpy array of numerical value are:-
#     1. bool
#     2. int
#     3. complex
#     4. float
# for the string:-
#     1. object

In [37]:
x = np.random.randint(10,100,(4,3))
x

array([[52, 70, 66],
       [72, 53, 57],
       [10, 84, 57],
       [19, 57, 27]])

In [38]:
x[1,2] #same as x[1][2] 

57

In [40]:
x[2,0]

10

In [41]:
x[2]

array([10, 84, 57])

In [43]:
x[-1]

array([19, 57, 27])

In [44]:
x[-2,-1] # -2 = second last row, -1 = last element

57

In [45]:
# x[start:end:stepsize,start:end:stepsize]

In [46]:
x[1:4]

array([[72, 53, 57],
       [10, 84, 57],
       [19, 57, 27]])

In [49]:
x[1:3,1:3] #row,column

array([[53, 57],
       [84, 57]])

In [50]:
y = np.random.randint(0,1000,(7,7))

In [51]:
y #get the value of 773,375,809,406

array([[195, 747, 148, 210, 529, 957, 732],
       [891,  79,  70, 176, 933,  64, 350],
       [ 76, 576, 773, 532, 907, 248, 278],
       [ 17, 925, 375,  40,   2, 180, 296],
       [345, 934, 809, 318, 247, 572, 908],
       [425, 629, 406, 810, 391, 109, 951],
       [357, 377, 367, 568, 447, 243, 645]])

In [55]:
y[2:6,2]

array([773, 375, 809, 406])

In [56]:
y[1:7:2,1:7:2]

array([[ 79, 176,  64],
       [925,  40, 180],
       [629, 810, 109]])

# Array slicing as views

In [57]:
y

array([[195, 747, 148, 210, 529, 957, 732],
       [891,  79,  70, 176, 933,  64, 350],
       [ 76, 576, 773, 532, 907, 248, 278],
       [ 17, 925, 375,  40,   2, 180, 296],
       [345, 934, 809, 318, 247, 572, 908],
       [425, 629, 406, 810, 391, 109, 951],
       [357, 377, 367, 568, 447, 243, 645]])

In [58]:
a = y[1:7:2,1:7:2]

In [59]:
a

array([[ 79, 176,  64],
       [925,  40, 180],
       [629, 810, 109]])

In [60]:
a[0,0] = 999

In [61]:
a

array([[999, 176,  64],
       [925,  40, 180],
       [629, 810, 109]])

In [62]:
y #change in original value of array

array([[195, 747, 148, 210, 529, 957, 732],
       [891, 999,  70, 176, 933,  64, 350],
       [ 76, 576, 773, 532, 907, 248, 278],
       [ 17, 925, 375,  40,   2, 180, 296],
       [345, 934, 809, 318, 247, 572, 908],
       [425, 629, 406, 810, 391, 109, 951],
       [357, 377, 367, 568, 447, 243, 645]])

In [63]:
a = y[1:7:2,1:7:2].copy()

In [64]:
a

array([[999, 176,  64],
       [925,  40, 180],
       [629, 810, 109]])

In [65]:
a[0,1] = 20

In [66]:
a

array([[999,  20,  64],
       [925,  40, 180],
       [629, 810, 109]])

In [67]:
y #no change 

array([[195, 747, 148, 210, 529, 957, 732],
       [891, 999,  70, 176, 933,  64, 350],
       [ 76, 576, 773, 532, 907, 248, 278],
       [ 17, 925, 375,  40,   2, 180, 296],
       [345, 934, 809, 318, 247, 572, 908],
       [425, 629, 406, 810, 391, 109, 951],
       [357, 377, 367, 568, 447, 243, 645]])

In [68]:
y.shape

(7, 7)

In [75]:
np.random.seed(3) #fixed the value of the array which is generated random
z = np.random.randint(0,100,(5,3))

In [76]:
z

array([[24,  3, 56],
       [72,  0, 21],
       [19, 74, 41],
       [10, 21, 38],
       [96, 20, 44]])

In [77]:
z.reshape(3,5) #new shape but the number of element should be same

array([[24,  3, 56, 72,  0],
       [21, 19, 74, 41, 10],
       [21, 38, 96, 20, 44]])

In [78]:
# z.reshape(3,6) shows the error which is that number of element is change

In [79]:
#concatenate
np.random.seed(3)
a = np.random.randint(0,100,(2,3))
b = np.random.randint(5,500,(2,3))

In [80]:
a

array([[24,  3, 56],
       [72,  0, 21]])

In [81]:
b

array([[152, 207, 368],
       [174, 143, 410]])

In [82]:
np.concatenate([a,b])

array([[ 24,   3,  56],
       [ 72,   0,  21],
       [152, 207, 368],
       [174, 143, 410]])

In [85]:
np.vstack([a,b])

array([[ 24,   3,  56],
       [ 72,   0,  21],
       [152, 207, 368],
       [174, 143, 410]])

In [86]:
np.concatenate([a,b], axis=1) #place one next to each other

array([[ 24,   3,  56, 152, 207, 368],
       [ 72,   0,  21, 174, 143, 410]])

In [87]:
np.hstack([a,b])

array([[ 24,   3,  56, 152, 207, 368],
       [ 72,   0,  21, 174, 143, 410]])

# Mathematical Operations on Numpy Arrays

In [88]:
x = np.arange(4)

In [89]:
x

array([0, 1, 2, 3])

In [90]:
x + 5

array([5, 6, 7, 8])

In [91]:
x - 2

array([-2, -1,  0,  1])

In [92]:
x / 2

array([0. , 0.5, 1. , 1.5])

In [93]:
x * 2

array([0, 2, 4, 6])

In [94]:
x // 2

array([0, 0, 1, 1], dtype=int32)

In [95]:
x % 2

array([0, 1, 0, 1], dtype=int32)

In [96]:
x ** 2

array([0, 1, 4, 9])

In [97]:
np.add(x,2)

array([2, 3, 4, 5])

In [98]:
np.subtract(x,2)

array([-2, -1,  0,  1])

# Boolean Indexing

In [99]:
z

array([[24,  3, 56],
       [72,  0, 21],
       [19, 74, 41],
       [10, 21, 38],
       [96, 20, 44]])

In [100]:
z > 50

array([[False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [101]:
z[z>50]

array([56, 72, 74, 96])

In [102]:
np.exp(z)

array([[2.64891221e+10, 2.00855369e+01, 2.09165950e+24],
       [1.85867175e+31, 1.00000000e+00, 1.31881573e+09],
       [1.78482301e+08, 1.37338298e+32, 6.39843494e+17],
       [2.20264658e+04, 1.31881573e+09, 3.18559318e+16],
       [4.92345829e+41, 4.85165195e+08, 1.28516001e+19]])

In [103]:
np.exp2(z)

array([[1.67772160e+07, 8.00000000e+00, 7.20575940e+16],
       [4.72236648e+21, 1.00000000e+00, 2.09715200e+06],
       [5.24288000e+05, 1.88894659e+22, 2.19902326e+12],
       [1.02400000e+03, 2.09715200e+06, 2.74877907e+11],
       [7.92281625e+28, 1.04857600e+06, 1.75921860e+13]])

In [106]:
np.power(2,3)

8

In [109]:
np.log(z)

C:\Users\raths\AppData\Local\Temp\ipykernel_24936\2047398432.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(z)


array([[3.17805383, 1.09861229, 4.02535169],
       [4.27666612,       -inf, 3.04452244],
       [2.94443898, 4.30406509, 3.71357207],
       [2.30258509, 3.04452244, 3.63758616],
       [4.56434819, 2.99573227, 3.78418963]])

In [110]:
np.var(z)

735.5288888888888

In [111]:
np.std(z)

27.120635849642035

In [112]:
np.std(z,axis=0) #standard deviation

array([33.67135281, 26.61277889, 11.296017  ])

In [113]:
np.min(z)

0

In [114]:
np.max(z)

96

In [115]:
np.argmin(z) #index position of minimum value

4

In [116]:
np.argmax(z) #index position of maximum value

12